### ISSUE TITLE
building using coq nix packages

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#471]
https://github.com/coq-community/manifesto/wiki/Continuous-Integration-with-Nix#generic-setup

**Comment by andres-erbsen** [comment]
Example:

```yaml
image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
packages:
  - nixpkgs.coq_8_8
  - nixpkgs.gnumake
sources:
  - https://github.com/mit-plv/fiat-crypto
tasks:
  - build: |
      cd fiat-crypto
      make "-j$(nproc)"
```
https://builds.sr.ht/~andres/job/17460

**Comment by andres-erbsen** [comment]
I can't figure out how to use the prebuilt binaries for coq master, though. Here is my current attempt:

```yaml
image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
tasks:
  - build: |
      nix-env -v \
        --prebuilt-only --extra-substituters https://coq.cachix.org \
        --trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= coq.cachix.org-1:Jgt0DwGAUo+wpxCM52k2V+E0hLoOzFPzvg94F65agtI=' \
        -f "https://github.com/coq/coq/tarball/master" \
        -i coq
      coqc --version
```

which does not manage to acquire coqc. omitting `--prebuilt-only` has it try to build coq, which timed out while running coqchk on the test suite.

**Comment by andres-erbsen** [comment]
I am out of ideas, continued at https://gitter.im/coq/coq?at=5c1ed0013c4093612c49ea27

**Comment by andres-erbsen** [comment]
Got it working with help from Théo Zimmermann, here goes:

```yaml
image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
packages:
  - nixpkgs.gnumake
sources:
  - https://github.com/mit-plv/fiat-crypto
tasks:
  - get_coq: |
      path=$(nix-prefetch-url --unpack 'https://github.com/coq/coq/tarball/master' --name source 2>&1 | tee /dev/stderr | grep -m1 '^path is' | cut -d\' -f2)
      nix-env -if "$path" --extra-substituters "https://coq.cachix.org" --trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= coq.cachix.org-1:Jgt0DwGAUo+wpxCM52k2V+E0hLoOzFPzvg94F65agtI="
      coqc --version
  - build: |
      cd fiat-crypto
      make "-j$(nproc)"
```

- `--name source` is essential for getting hashes to match and the cache to work
- sometimes the cache still fails when the commit has been merged to master but CI hasn't finished yet
